### ISSUE TITLE
当目标响应码是302时的bug

### ISSUE THREAD

**Issue by AgeloVito** [wyzxxz/shiro_rce#1]
find http 302, the target url seems is: https://xxxxx.xxx.cn/index.do
当响应状态码是302时，程序无法继续guess shiro key

建议去掉状态码验证逻辑，强行探测

**Comment by wyzxxz** [comment]
默认返回包set-cookie有rememberMe=deleteMe就会探测，和状态码无关，增加了自定义key测试，你看下是否能解决你的问题，如果还不行，如果方便的话，可以提供下环境调试一下。

**Comment by AgeloVito** [comment]
麻烦提供一下联系方式，方便我提供测试用例




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wyzxxz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 晚上8:37
收件人:&nbsp;"wyzxxz/shiro_rce"<shiro_rce@noreply.github.com&gt;;
抄送:&nbsp;"彭强亮"<917077172@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wyzxxz/shiro_rce] 当目标响应码是302时的bug (#1)





 
默认返回包set-cookie有rememberMe=deleteMe就会探测，和状态码无关，增加了自定义key测试，你看下是否能解决你的问题，如果还不行，如果方便的话，可以提供下环境调试一下。

**Comment by wyzxxz** [comment]
QQ 342070435
