### ISSUE TITLE
为什么扫描利用链的时候没有扫描 CommonsCollections10

### ISSUE THREAD

**Issue by mntn0x** [wyzxxz/shiro_rce#7]
我直接clone的项目，在本地运行时，没有出现readme里面那么多利用链扫描，请问这个是怎么解决？

**Comment by wyzxxz** [comment]
调试用的，所以没对外加这个，最新版这块用了原来的ysoserial，https://github.com/frohoff/ysoserial

**Comment by mntn0x** [comment]
&nbsp;


---原始邮件---
发件人: &quot;wyzxxz&quot;<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 下午2:47
收件人: &quot;wyzxxz/shiro_rce&quot;<shiro_rce@noreply.github.com&gt;;
抄送: &quot;mntn0x&quot;<1551763028@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [wyzxxz/shiro_rce] 为什么扫描利用链的时候没有扫描 CommonsCollections10 (#7)




 
调试用的，所以没对外加这个，最新版这块用了原来的ysoserial，https://github.com/frohoff/ysoserial
 
&mdash;
