### ISSUE TITLE
错误: 找不到或无法加载主类 Shiro

### ISSUE THREAD

**Issue by sunkeepero** [wyzxxz/shiro_rce#8]
![image](https://user-images.githubusercontent.com/36943157/82864195-9be98e00-9f56-11ea-8bbc-04743bc25e67.png)
大佬，这儿的Shiro是啥，报错怎么处理，麻烦回答一下，谢谢！

**Comment by wyzxxz** [comment]
参考文档，直接 java -jar shiro_tool.jar https://xx.xx.xx.xx  就行

**Comment by sunkeepero** [comment]
大佬，我执行完是这样的，可以直接传shell吗，麻烦指导我一下，我太菜了，希望大佬别生气，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wyzxxz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午2:05
收件人:&nbsp;"wyzxxz/shiro_rce"<shiro_rce@noreply.github.com&gt;;
抄送:&nbsp;"安暖相伴"<984084954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wyzxxz/shiro_rce] 错误: 找不到或无法加载主类 Shiro (#8)





 
参考文档，直接 java -jar shiro_tool.jar https://xx.xx.xx.xx  就行

**Comment by wyzxxz** [comment]
写SHELL需要自己找下web目录然后上传一下，这个只是基础的命令执行工具

**Comment by sunkeepero** [comment]
哦，好的大佬，很感谢能够回复我！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wyzxxz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午2:18
收件人:&nbsp;"wyzxxz/shiro_rce"<shiro_rce@noreply.github.com&gt;;
抄送:&nbsp;"安暖相伴"<984084954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wyzxxz/shiro_rce] 错误: 找不到或无法加载主类 Shiro (#8)





 
写SHELL需要自己找下web目录然后上传一下，这个只是基础的命令执行工具

**Comment by wyzxxz** [comment]
刚把描述这块的改了，重新打包了，可以重新下载一下。

**Comment by sunkeepero** [comment]
好的，谢谢！大佬，能加个VX吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wyzxxz-紫霞仙子大佬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午2:34
收件人:&nbsp;"wyzxxz/shiro_rce"<shiro_rce@noreply.github.com&gt;;
抄送:&nbsp;"安暖相伴"<984084954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wyzxxz/shiro_rce] 错误: 找不到或无法加载主类 Shiro (#8)





 
刚把描述这块的改了，重新打包了，可以重新下载一下。

**Comment by wyzxxz** [comment]
vampire_paopao
